REQUEST_ADDRESS = 'RequestAddress'
GET_ADDRESS = 'GetAddress'
NOT_FOUND_ADDRESS = 'NotFoundAddress'
PERSIST_ADDRESS = 'PersistAddress'
GET_REGISTRY = 'GetRegistry'

events = [REQUEST_ADDRESS, GET_ADDRESS, PERSIST_ADDRESS, NOT_FOUND_ADDRESS, GET_REGISTRY]
